version: "3.9"

services:
  db:
    image: postgres
    container_name: ogb_postgres_dev
    environment:
      - POSTGRES_DB=opengenomebrowser_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/pg_data
    volumes:
      - ./ogb_container/pg_data:/pg_data


  web:
    build: .
    container_name: ogb_web_dev
    env_file:
      - development.env
    command: /opengenomebrowser/init.sh
    volumes:
      - ./:/opengenomebrowser/
      - ./database:/database
    ports:
      - "8000:8000"
    depends_on:
      - db
