# Generated by Django 3.1.4 on 2021-01-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='cds_tool_ffn_file',
            field=models.CharField(max_length=200),
        ),
    ]
