# Generated by Django 3.1.5 on 2021-01-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210107_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='anno_type',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='genome',
            name='cds_tool_ffn_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
