# Generated by Django 3.1.6 on 2021-02-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210119_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='BUSCO_percent_single',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
