# Generated by Django 3.1.6 on 2021-02-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210209_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='name',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
