# Generated by Django 3.1.7 on 2021-03-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210211_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='coregenomedendrogram',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
