# Generated by Django 3.2 on 2021-04-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_coregenomedendrogram_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coregenomedendrogram',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='growth_condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Growth condition'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genomesimilarity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
