# Generated by Django 3.2.2 on 2021-05-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210423_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='bioproject_accession',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bioproject accession'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='biosample_accession',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Biosample accession'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='env_broad_scale',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Broad isolation environment'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='env_local_scale',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Local isolation environment'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='env_medium',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Environment medium'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='genome_accession',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Genome accession'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='literature_references',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Literature references'),
        ),
    ]
