# Generated by Django 3.2.4 on 2021-07-02 12:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210511_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genome',
            name='env_broad_scale',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='env_local_scale',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='env_medium',
        ),
        migrations.AddField(
            model_name='genome',
            name='env_broad_scale_new',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='Broad isolation environment'),
        ),
        migrations.AddField(
            model_name='genome',
            name='env_local_scale_new',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='Local isolation environment'),
        ),
        migrations.AddField(
            model_name='genome',
            name='env_medium_new',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='Environment medium'),
        ),
    ]
