# Generated by Django 3.2.5 on 2021-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210702_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
