# Generated by Django 3.2.7 on 2021-09-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_organism_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='COG',
            field=models.JSONField(default=dict),
        ),
    ]
