# Generated by Django 4.0.2 on 2022-02-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_genome_cog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomecontent',
            name='ani_similarity',
            field=models.ManyToManyField(through='website.GenomeSimilarity', to='website.GenomeContent'),
        ),
    ]
