from .calculate_orthofinder import calculate_orthofinder as calculate_core_genome_dendrogram
from .calculate_gendiscal import calculate_gendiscal as calculate_genome_similarity
from .calculate_dotplot import calculate_dotplot
from .calculate_blast import calculate_blast
