from .Home import home_view
from .StrainDetailView import StrainDetailView
from .GenomeTable import genome_list_view
from .GenomeDetailView import GenomeDetailView
from .GenomeTableAjax import GenomeTableAjax
from .LoadTableScript import render_script
from .PathwayView import pathway_view
from .TaxIDDetailView import TaxIDDetailView
from .GeneDetailView import GeneDetailView
from .AnnotationSearch import annotation_view
from .AnnotationDetailView import AnnotationDetailView
from .Trees import trees
from .Blast import blast_view
from .Api import Api
from .Download import download_view
from .ClickMenu import click_view
from .CompareGenes import CompareGenes